server:
    port: 11112
spring:
    profiles:
        active: dev
---
server:
    port: 8081
spring:
    profiles: dev
---
server:
    port: 8086
spring:
    profiles: prod


#person:
#    lastName: zhangsan
#    age: 20
#    boss: false
#    birth: 2019/09/09
#    maps: {k1:v1, k2:2}
#    lists:
#      - cat
#      - dog
#      - pig
#    dog:
#      name: 小狗
#      age: 2

